server:
  port: 8080
  tomcat:
    max-http-post-size: 314572800
spring:
  main:
    banner-mode: "off"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 300MB
  application:
    name: news-gateway-server
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ReadTimeout: 600000
  SocketTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  okhttp:
    enabled: true
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://sq:Sq888@neikan.shengquan.com:8761/eureka/
    eureka-connection-idle-timeout-seconds: 600000
    eureka-server-connect-timeout-seconds: 600000
    eureka-server-read-timeout-seconds: 600000
  instance:
    prefer-ip-address: true
    status-page-url: http://neikan.shengquan.com:${server.port}/routes
logging:
  level:
    root: error
zuul:
  ribbon:
    eager-load:
      enabled: true
  sensitiveHeaders:
  prefix: /rest
  host:
    max-total-connections: 500
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
  routes:
    news-admin-service:
       path: /admins/**
       stripPrefix: false
    news-periodical-service:
       path: /periodicals/**
       stripPrefix: false
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://sq:Sq888@neikan.shengquan.com:8761/eureka/
  instance:
    status-page-url: http://neikan.shengquan.com:${server.port}/routes
logging:
  level:
    root: info